name: settings_tiles
description: "A collection of settings tiles to easily create a settings screen"

repository: https://github.com/maelchiotti/settings_tiles
issue_tracker: https://github.com/maelchiotti/settings_tiles/issues

version: 6.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  easy_localization: ^3.0.7+1
  flex_color_picker: ^3.7.1

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1

dev_dependencies:
  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0
